In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.4'

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.eye(4).shape

(4, 4)

In [6]:
np.eye(4).size

16

In [8]:
np.eye(4).ndim

2

In [9]:
np.eye(4).dtype

dtype('float64')

In [11]:
np.empty([3,3],np.int32)

array([[1409991392,      32716,          0],
       [         0,  825831987,         48],
       [1409286272,      32716,         45]], dtype=int32)

In [13]:
np.zeros([3,3],np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [14]:
np.ones([3,3],np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,15,1.4,np.float32)

array([ 5.      ,  6.4     ,  7.8     ,  9.200001, 10.6     , 12.      ,
       13.400001, 14.800001], dtype=float32)

In [19]:
np.arange(10)[slice(2,7,2)]

array([2, 4, 6])

In [20]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
np.arange(10).reshape(5,2).T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])